// auto-generated by circomkit
pragma circom 2.0.0;

include "../../zkDutchAuction8.circom";

component main {public[commitments, commitmentContractAddress, makerMinimumPrice, makerMaximumAmount]} = zkDutchAuction8();
